# Generated by Django 3.1.3 on 2021-01-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=False)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
